baseurl = "https://priceoffreedom.us/"
title = "Price of Freedom Museum"
theme = "hugo-universal-theme"
languageCode = "en-us"
defaultContentLanguage = "en"

summaryLength = 70
pluralizelisttitles = false

[services]
    [services.disqus]
        shortname = ""
    [services.googleAnalytics]
        id = ""

[pagination]
    pagerSize = 10

# Main menu
[menu]

[[menu.main]]
    name       = "Home"
    identifier = "home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Reviews"
    identifier = "reviews"
    url        = "/reviews/"
    weight     = 2

[[menu.main]]
    name       = "Media"
    identifier = "media"
    url        = "/media/"
    weight     = 3

[[menu.main]]
    name       = "Blog"
    identifier = "blog"
    url        = "/posts/"
    weight     = 4

[[menu.main]]
    name       = "Donate"
    identifier = "donate"
    url        = "https://givebutter.com/Ci42c2"
    weight     = 5

# Top bar social links
[[menu.topbar]]
    weight = 1
    name = "Facebook"
    url = "https://www.facebook.com/ThePriceOfFreedomMuseum/"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[params]
    viewMorePostLink = "/posts/"
    author = "Price of Freedom Museum"
    defaultKeywords = ["military", "museum", "veterans", "freedom", "china grove", "north carolina"]
    mainSections = ["posts"]
    defaultDescription = "Price of Freedom Museum - Honoring Service Men & Women"

    facebook_site = "ThePriceOfFreedomMuseum"
    default_sharing_image = "img/logo.png"

    enableGoogleMaps = false

    style = "olive"

    about_us = "<p>The Price of Freedom Museum honors Service Men & Women. Located in China Grove, NC, the museum houses a collection of military uniforms and memorabilia preserving the legacy of those who served.</p>"
    copyright = "Copyright (c) 2026, Price of Freedom Museum. All rights reserved."

    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Price of Freedom Museum"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

    address = """<p class="text-uppercase"><strong>Price of Freedom Museum</strong>
        <br>China Grove, NC
        <br>
        <br><a href="https://www.facebook.com/ThePriceOfFreedomMuseum/">Visit us on Facebook</a>
      </p>
      """

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[permalinks]
    posts = "/posts/:contentbasename/"

# Top bar
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Honoring Service Men & Women</p>
      <p class="hidden-md hidden-lg">
      <a href="https://www.facebook.com/ThePriceOfFreedomMuseum/" data-animate-hover="pulse"><i class="fab fa-facebook"></i></a>
      </p>
      """

[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 3000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3

[params.testimonials]
    enable = true
    title = "What People Say"
    subtitle = "Visitors and supporters share their experiences with the Price of Freedom Museum."

[params.see_more]
    enable = true
    icon = "fas fa-hand-holding-heart"
    title = "Support the Museum"
    subtitle = "Your donation helps preserve the legacy of our service men and women for future generations."
    link_url = "https://givebutter.com/Ci42c2"
    link_text = "Donate Online"

[params.clients]
    enable = false

[params.recent_posts]
    enable = true
    title = "Latest News"
    subtitle = "Stay up to date with the latest events and news from the Price of Freedom Museum."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
